### ISSUE TITLE
sed error in device install script

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#495] opened 2023-09-21 20:20 UTC
### Describe the bug

When installing on the device I see an 'sed' error (It does not seem to effect anything but still)

```
bash -c "$(curl -fsSL https://getsshnpd.noports.com)" -- --args "-s -u -v"
  [X] Missing required dependency: unzip
Client address (e.g. @alice_client): @lorawan123_client
Device address (e.g. @alice_device): @lorawan123_device
Device name: dragino

Downloading sshnpd from https://github.com/atsign-foundation/sshnoports/releases/download/v3.4.2/sshnp-linux-arm.tgz
Installed binaries: sshnpd at_activate sshrv
sed: can't read /home/lorawan123/.local/bin/sshnpd@lorawan123_client: No such file or directory
Installed cron job: '@reboot nohup /home/lorawan123/.local/bin/sshnpd@lorawan123_client > /home/lorawan123/.sshnpd/logs/@lorawan123_client.log 2> /home/lorawan123/.sshnpd/logs/@lorawan123_client.err'
Installed cron job: '40 6 * * * logrotate -f /home/lorawan123/.sshnpd/logs/@lorawan123_client.log'
Service entry added: sshnpd@lorawan123_client cron
Starting sshnpd@lorawan123_client service...

Installation complete!
```

### Steps to reproduce

1. use install script

### Expected behavior

no errors

### Smartphones

- armbian (debian)

**Comment by xavierchanth** [comment] 2023-11-21 20:35
Going to close this ticket, it's non breaking, and this installer is soon to be replaced by #537 .

The problem is that we try to sed a file when renaming/installing, but that file doesn't exist on install so it complains. (but doesn't break anything)

**Closed as completed by xavierchanth** 2023-11-21 20:35 UTC
Labels: bug
