### ISSUE TITLE
No Ports Desktop Enhancements

### ISSUE THREAD

**Issue by ksanty** [atsign-foundation/noports#786] opened 2024-02-01 21:23 UTC
Just a couple of notes on V3

- [x] Fix app typos highlighted by Jen in the Figma file

_Onboarding screen_
- [x] There is a black outline around on the Left-side and bottom -> Can we get the background to fully cover?
- [x] Logo is blurry (could we get an SVG)
- [x] Can we increase the distance between text and button (theres a large distance on bottom of section)
- [x] Can we get a medium weight on button text
> ![Image](https://github.com/atsign-foundation/noports/assets/84993403/ef2bbd56-f795-4a99-99d4-226703709761)

_Navigation_
- [x] Can we get a left and margin increase on the sides of the icons (see bellow)
![Image](https://github.com/atsign-foundation/noports/assets/84993403/914f23cd-ba72-4dde-a58a-1b74cc088709)

_Dashboard screen_
- [x] Can we get the same margin on left and right side (see yellow on image bellow)
> ![Image](https://github.com/atsign-foundation/noports/assets/84993403/524fd88c-e5fb-4251-9b49-0f2fb0de3f11)
- [x] Home Screen - can we do the following (as user hovers it changes
> ![Image](https://github.com/atsign-foundation/noports/assets/84993403/615172f8-acbd-4607-96d1-83e3afbb4f26)
- [x] Remove the import button
- [x] Remove the export menu item
- [x] change local forwarding port hint message to "Local port to use for doing tcp forwarding (ephemeral if set to 0)"
- [x] reduce width between ssh private key and share ssh private key

**Comment by CurtlyCritchlow** [comment] 2024-02-07 14:20
@Dariamarg and @ksanty does the narrower navigation rail with the smaller margin looks better or the one with the larger margin?

**Comment by ksanty** [comment] 2024-02-07 16:13
> @Dariamarg and @ksanty does the narrower navigation rail with the smaller margin looks better or the one with the larger margin?

I don't have access to test @CurtlyCritchlow I think I transposed this ticket for @Dariamarg (I don't remember) Daria is in mid-terms, so hopefully she can get to testing this soon.  Do you have an image capture and I can give my 2 cents?

**Comment by CurtlyCritchlow** [comment] 2024-02-07 16:22
> > @Dariamarg and @ksanty does the narrower navigation rail with the smaller margin looks better or the one with the larger margin?
> 
> I don't have access to test @CurtlyCritchlow I think I transposed this ticket for @Dariamarg (I don't remember) Daria is in mid-terms, so hopefully she can get to testing this soon.
<img width="671" alt="Screenshot 2024-02-07 at 12 18 50 PM" src="https://github.com/atsign-foundation/noports/assets/44856451/86545a69-4460-4238-b7d6-6c9e1c758a6a">

<img width="671" alt="Screenshot 2024-02-07 at 12 21 27 PM" src="https://github.com/atsign-foundation/noports/assets/44856451/a80895c1-d7e5-452d-94dd-4ba9619ecfca">


 @ksanty Screenshot of the two version above.

**Comment by ksanty** [comment] 2024-02-07 16:44
> > > @Dariamarg and @ksanty does the narrower navigation rail with the smaller margin looks better or the one with the larger margin?
> > 
> > 
> > I don't have access to test @CurtlyCritchlow I think I transposed this ticket for @Dariamarg (I don't remember) Daria is in mid-terms, so hopefully she can get to testing this soon.
> 
> <img alt="Screenshot 2024-02-07 at 12 18 50 PM" width="671" src="https://private-user-images.githubusercontent.com/44856451/303054288-86545a69-4460-4238-b7d6-6c9e1c758a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyNDcsIm5iZiI6MTcwNzMyMjk0NywicGF0aCI6Ii80NDg1NjQ1MS8zMDMwNTQyODgtODY1NDVhNjktNDQ2MC00MjM4LWI3ZDYtNmM5ZTFjNzU4YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGJiZjI3Y2U0NjY1MTBkYzFjMmIzMTExNjczZTk1MTc0NzVkMzQ1ZmE5NWYyYjAxNjI5NDE0ZDJjMTMwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVJLQj01Ei_Qmx548FxdxPLz4bQ9hk1MxXu_Ax-YBZ4"> <img alt="Screenshot 2024-02-07 at 12 21 27 PM" width="671" src="https://private-user-images.githubusercontent.com/44856451/303054992-a80895c1-d7e5-452d-94dd-4ba9619ecfca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyNDcsIm5iZiI6MTcwNzMyMjk0NywicGF0aCI6Ii80NDg1NjQ1MS8zMDMwNTQ5OTItYTgwODk1YzEtZDdlNS00NTJkLTk0ZGQtNGJhOTYxOWVjZmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGUwYjE0MjU4OGU2OTQwZDliOTBkYjU3Y2I5OGFlMjgyMzgxODI1MjE2NWU4ODBkMjk4ZGJiNGRlZmU0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7cTuKY7GM7MdHfw0YMe_dfqA2PWv7OCyxIH1u5PW0s">
> @ksanty Screenshot of the two version above.

I like the narrow better @CurtlyCritchlow but then I think the icons need to be scaled down.

**Comment by ksanty** [comment] 2024-02-07 16:47
> > > > @Dariamarg and @ksanty does the narrower navigation rail with the smaller margin looks better or the one with the larger margin?
> > > 
> > > 
> > > I don't have access to test @CurtlyCritchlow I think I transposed this ticket for @Dariamarg (I don't remember) Daria is in mid-terms, so hopefully she can get to testing this soon.
> > 
> > 
> > <img alt="Screenshot 2024-02-07 at 12 18 50 PM" width="671" src="https://private-user-images.githubusercontent.com/44856451/303054288-86545a69-4460-4238-b7d6-6c9e1c758a6a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyNDcsIm5iZiI6MTcwNzMyMjk0NywicGF0aCI6Ii80NDg1NjQ1MS8zMDMwNTQyODgtODY1NDVhNjktNDQ2MC00MjM4LWI3ZDYtNmM5ZTFjNzU4YTZhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTczZGJiZjI3Y2U0NjY1MTBkYzFjMmIzMTExNjczZTk1MTc0NzVkMzQ1ZmE5NWYyYjAxNjI5NDE0ZDJjMTMwNjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.CVJLQj01Ei_Qmx548FxdxPLz4bQ9hk1MxXu_Ax-YBZ4"> <img alt="Screenshot 2024-02-07 at 12 21 27 PM" width="671" src="https://private-user-images.githubusercontent.com/44856451/303054992-a80895c1-d7e5-452d-94dd-4ba9619ecfca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDczMjMyNDcsIm5iZiI6MTcwNzMyMjk0NywicGF0aCI6Ii80NDg1NjQ1MS8zMDMwNTQ5OTItYTgwODk1YzEtZDdlNS00NTJkLTk0ZGQtNGJhOTYxOWVjZmNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMDclMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjA3VDE2MjIyN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTk2MGUwYjE0MjU4OGU2OTQwZDliOTBkYjU3Y2I5OGFlMjgyMzgxODI1MjE2NWU4ODBkMjk4ZGJiNGRlZmU0YjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.r7cTuKY7GM7MdHfw0YMe_dfqA2PWv7OCyxIH1u5PW0s">
> > @ksanty Screenshot of the two version above.
> 
> I like the narrow better @CurtlyCritchlow but then I think the icons need to be scaled down.  @Dariamarg what do you think?

**Comment by Dariamarg** [comment] 2024-02-07 19:36
I like the one with the spacing, just think it gives it a little more room :)

**Comment by ksanty** [comment] 2024-02-07 19:42
> I like the one with the spacing, just think it gives it a little more room :)

Ok, so the wider one?  @CurtlyCritchlow go with @Dariamarg recco.  My thought was we would have more working space on the right for people using the GUI.  :-)

**Comment by CurtlyCritchlow** [comment] 2024-03-18 12:51
@ksanty,  v1.0.0(4) build available on test flight, please retest and confirm these fixes were implemented. If they were, please close this ticket.

**Closed as completed** 2024-03-18 15:17 UTC

**Comment by ksanty** [comment] 2024-03-18 15:19
> [@ksanty](https://github.com/ksanty), v1.0.0(4) build available on test flight, please retest and confirm these fixes were implemented. If they were, please close this ticket.

@CurtlyCritchlow I don't have a way to test the GUI.  Can @Dariamarg test it?  I closed the ticket regardless. What did you decided to do with the nav bar?

**Comment by CurtlyCritchlow** [comment] 2024-03-18 15:22
I went for the wider nav bar.

**Comment by ksanty** [comment] 2024-03-18 16:12
> I went for the wider nav bar.

Great!  @Dariamarg remembers this and thinks I created the ticket for her.  Not unlike me.  She has it on her list.

**Comment by CurtlyCritchlow** [comment] 2024-03-18 16:14
> > I went for the wider nav bar.
> 
> Great! @Dariamarg remembers this and thinks I created the ticket for her. Not unlike me. She has it on her list.

Great, and thanks for the ticket, it was super helpful in guiding me on what to change.

**Comment by Dariamarg** [comment] 2024-03-18 17:54
All changes are made - I have a couple new notes:

- [ ] I think font size might be too small in some areas (might just be me)
- [ ] Could we get these two button menus to have the same layout (whichevers easiest for you)
> ![Image](https://github.com/atsign-foundation/noports/assets/84993403/652ea70f-4bf2-4cd7-9b09-aaf33f598a34)
> ![Image](https://github.com/atsign-foundation/noports/assets/84993403/d78a93ae-e5ab-4b50-ae29-20d5f0e60e49)

- [ ]  This was intended for when we had more than one option
 >  Home Screen - can we do the following
- Can we do something like this
![Image](https://github.com/atsign-foundation/noports/assets/84993403/d9ee40ea-1799-4899-9d0f-ae23666f95b8)

**Comment by CurtlyCritchlow** [comment] 2024-03-20 14:24
@Dariamarg, since this is new feedback, can you create it in a separate ticket?
