### ISSUE TITLE
Unable to install Python version of sshnpd on OpenWRT (Chirpstack)

### ISSUE THREAD

**Issue by cconstab** [atsign-foundation/noports#451] opened 2023-09-11 18:07 UTC
### Describe the bug

When installing the Python version on the the Chirpstack OpenWRT image the instructions fail with not being able to find ` #include <ffi.h>`

This seems to be easily fixed on Ubuntu/Linuyx but there is no opkg for ffi-dev

### Steps to reproduce

1. First i built an PI image from `https://www.chirpstack.io/docs/getting-started/raspberry-pi.html`
2. Second I followed the instructions to install the Python version of sshnp
3. I had  to install the missing components using `opkg` built into the OpenWRT image
4. Stall at the last step as a Header file is missing

### Expected behavior

Should install cleanly or we should have an opkg for sshnpd ?

### Screenshots

```
root@chirpstack-548a0f:~/at_python#  pip install .
Processing /root/at_python
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cffi==1.15.1 (from at_python==0.0.1)
  Using cached cffi-1.15.1.tar.gz (508 kB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting cryptography==41.0.3 (from at_python==0.0.1)
  Using cached cryptography-41.0.3.tar.gz (630 kB)
  Installing build dependencies ... error
  error: subprocess-exited-with-error

  × pip subprocess to install build dependencies did not run successfully.
  │ exit code: 1
  ╰─> [92 lines of output]
      Collecting setuptools>=61.0.0
        Obtaining dependency information for setuptools>=61.0.0 from https://files.pythonhosted.org/packages/95/79/6b47c6a872b40743a480687dc0c79ffb4202710789f3e4d54a84fff8b550/setuptools-68.2.1-py3-none-any.whl.metadata
        Using cached setuptools-68.2.1-py3-none-any.whl.metadata (6.3 kB)
      Collecting wheel
        Obtaining dependency information for wheel from https://files.pythonhosted.org/packages/b8/8b/31273bf66016be6ad22bb7345c37ff350276cfd46e389a0c2ac5da9d9073/wheel-0.41.2-py3-none-any.whl.metadata
        Using cached wheel-0.41.2-py3-none-any.whl.metadata (2.2 kB)
      Collecting cffi>=1.12
        Using cached cffi-1.15.1.tar.gz (508 kB)
        Installing build dependencies: started
        Installing build dependencies: finished with status 'done'
        Getting requirements to build wheel: started
        Getting requirements to build wheel: finished with status 'done'
        Preparing metadata (pyproject.toml): started
        Preparing metadata (pyproject.toml): finished with status 'done'
      Collecting setuptools-rust>=0.11.4
        Obtaining dependency information for setuptools-rust>=0.11.4 from https://files.pythonhosted.org/packages/5b/be/8d88f5982d61fefa2cbc633b167d2553875169eee136b584089667c37e93/setuptools_rust-1.7.0-py3-none-any.whl.metadata
        Using cached setuptools_rust-1.7.0-py3-none-any.whl.metadata (4.8 kB)
      Collecting pycparser (from cffi>=1.12)
        Using cached pycparser-2.21-py2.py3-none-any.whl (118 kB)
      Collecting semantic-version<3,>=2.8.2 (from setuptools-rust>=0.11.4)
        Using cached semantic_version-2.10.0-py2.py3-none-any.whl (15 kB)
      Collecting typing-extensions>=3.7.4.3 (from setuptools-rust>=0.11.4)
        Obtaining dependency information for typing-extensions>=3.7.4.3 from https://files.pythonhosted.org/packages/ec/6b/63cc3df74987c36fe26157ee12e09e8f9db4de771e0f3404263117e75b95/typing_extensions-4.7.1-py3-none-any.whl.metadata
        Using cached typing_extensions-4.7.1-py3-none-any.whl.metadata (3.1 kB)
      Using cached setuptools-68.2.1-py3-none-any.whl (807 kB)
      Using cached wheel-0.41.2-py3-none-any.whl (64 kB)
      Using cached setuptools_rust-1.7.0-py3-none-any.whl (25 kB)
      Using cached typing_extensions-4.7.1-py3-none-any.whl (33 kB)
      Building wheels for collected packages: cffi
        Building wheel for cffi (pyproject.toml): started
        Building wheel for cffi (pyproject.toml): finished with status 'error'
        error: subprocess-exited-with-error

        × Building wheel for cffi (pyproject.toml) did not run successfully.
        │ exit code: 1
        ╰─> [50 lines of output]
            /tmp/pip-build-env-50dtre_1/overlay/lib/python3.11/site-packages/setuptools/config/setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
            !!

                    ********************************************************************************
                    The license_file parameter is deprecated, use license_files instead.

                    By 2023-Oct-30, you need to update your project and remove deprecated calls
                    or your builds will no longer be supported.

                    See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
                    ********************************************************************************

            !!
              parsed = self.parsers.get(option_name, lambda x: x)(value)
            running bdist_wheel
            running build
            running build_py
            creating build
            creating build/lib.linux-armv7l-cpython-311
            creating build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/verifier.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/vengine_gen.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/vengine_cpy.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/setuptools_ext.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/recompiler.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/pkgconfig.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/model.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/lock.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/ffiplatform.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/error.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/cparser.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/commontypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/cffi_opcode.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/backend_ctypes.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/api.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/__init__.py -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/_cffi_include.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/parse_c_type.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/_embedding.h -> build/lib.linux-armv7l-cpython-311/cffi
            copying cffi/_cffi_errors.h -> build/lib.linux-armv7l-cpython-311/cffi
            running build_ext
            building '_cffi_backend' extension
            creating build/temp.linux-armv7l-cpython-311
            creating build/temp.linux-armv7l-cpython-311/c
            gcc -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -mfloat-abi=hard -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/Python-3.11.4=Python-3.11.4 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -Os -pipe -fno-caller-saves -fno-plt -fhonour-copts -mfloat-abi=hard -ffile-prefix-map=/builder/shared-workdir/build/sdk/build_dir/target-arm_cortex-a7+neon-vfpv4_musl_eabi/Python-3.11.4=Python-3.11.4 -Wformat -Werror=format-security -fstack-protector -D_FORTIFY_SOURCE=1 -Wl,-z,now -Wl,-z,relro -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-12.3.0_musl_eabi/usr/include -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-12.3.0_musl_eabi/include/fortify -I/builder/shared-workdir/build/sdk/staging_dir/toolchain-arm_cortex-a7+neon-vfpv4_gcc-12.3.0_musl_eabi/include -fPIC -DFFI_BUILDING=1 -DUSE__THREAD -DHAVE_SYNC_SYNCHRONIZE -I/usr/include/ffi -I/usr/include/libffi -I/usr/include/python3.11 -c c/_cffi_backend.c -o build/temp.linux-armv7l-cpython-311/c/_cffi_backend.o
            c/_cffi_backend.c:15:10: fatal error: ffi.h: No such file or directory
               15 | #include <ffi.h>
                  |          ^~~~~~~
            compilation terminated.
            error: command '/usr/bin/gcc' failed with exit code 1
            [end of output]

        note: This error originates from a subprocess, and is likely not a problem with pip.
        ERROR: Failed building wheel for cffi
      Failed to build cffi
      ERROR: Could not build wheels for cffi, which is required to install pyproject.toml-based projects
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× pip subprocess to install build dependencies did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.
root@chirpstack-548a0f:~/at_python#
```

### Smartphones

- Pi 4 - 4 GB

**Comment by cpswan** [comment] 2023-09-11 21:06
At first glance this is a problem with dependencies. When they’re already compiled (Python calls them ‘wheels’) they just get downloaded from PyPi, but if wheels aren’t there Python will try to compile locally from source, and that can run deeper into missing dependencies, in this case ffi.

What processor architecture is OpenWRT running on here?

**Comment by cpswan** [comment] 2023-09-12 09:37
@cconstab coming back to this I see Pi4 mentioned, so we're dealing with Arm. but it's unclear whether it's armv7 or arm64

Looking at https://pypi.org/project/cffi/#files I see aarch64 wheels, so I suspect the issue is we have a 32bit OS on 64bit hardware, though that's not unusual.

Can you verify the output of `uname -m` and also please clarify which version of python you got from opkg (`python3 --version`)?

**Comment by cpswan** [comment] 2023-10-04 13:07
Some progress (I hope)...

> [piwheels](https://www.piwheels.org/) is a Python package repository providing Arm platform wheels (pre-compiled binary Python packages) specifically for the Raspberry Pi, making pip installations much faster. Packages are natively compiled on Raspberry Pi 3 and 4 hardware using the Mythic Beasts Pi cloud.

Things work be default on Raspberry Pi OS, because:

> Raspberry Pi OS includes configuration for pip to use piwheels by default, which lives at /etc/pip.conf:

So... it should be possible to get Chirpstack (on a Pi) working by adding this to `/etc/pip.conf`:

```
[global]
extra-index-url=https://www.piwheels.org/simple
```

It also points the way to how we can host alternative wheels for key packages for other OS/ISA combinations where there aren't wheels on PyPI.

**Comment by cpswan** [comment] 2023-10-09 17:29
@cconstab I've got `sshnpdpy` running on Chirpstack (though I've not yet got a working connection to it):
![image](https://github.com/atsign-foundation/sshnoports/assets/478926/4d79fc6c-699c-4f37-b2ce-a5518cabda38)

Here's an archive of the wheels and libs I needed to copy over:

[wheels_libs.zip](https://github.com/atsign-foundation/sshnoports/files/12848762/wheels_libs.zip)

The wheels were built on Raspberry Pi OS running on a Pi4. That's where I also got the libs, except libc.so, which comes from the Pi2 image for OpenWRT.

Install the wheels with `pip3 install wheelname.whl` and make sure cffi is installed before things that depend on it.

**Comment by cpswan** [comment] 2023-10-10 08:30
@Xlin123 suggested passing a key into sshnp with the `-s` flag, which results in this stacktrace, because the default SSH daemon in OpenWRT is [Dropbear](https://matt.ucc.asn.au/dropbear/dropbear.html), which doesn't use ~/.ssh/authorized_keys

```
[Errno 2] No such file or directory: '/home/admin/.ssh/authorized_hosts'
Traceback (most recent call last):
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/./sshnpd.py", line 23, in main
    sshnpd.start()
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/lib/sshnpdclient.py", line 63, in start
    self._handle_notifications(self.at_client.queue, self.sshnp_callback)
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/lib/sshnpdclient.py", line 122, in _handle_notifications
    with open(f"{self.ssh_path}/authorized_hosts", "r") as read:
FileNotFoundError: [Errno 2] No such file or directory: '/home/admin/.ssh/authorized_hosts'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/./sshnpd.py", line 37, in <module>
    main()
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/./sshnpd.py", line 33, in main
    sshnpd.join()
  File "/home/admin/sshnoports-trunk/packages/sshnpdpy/lib/sshnpdclient.py", line 75, in join
    self.ssh_client.close()
AttributeError: 'NoneType' object has no attribute 'close'
```

**Comment by cpswan** [comment] 2023-10-10 09:31
More progress... With a fresh image of Chirpstack v4.2.0:

```
opkg update
opkg install python3-pip python3-bcrypt python3-cffi python3-cryptography python3-pynacl unzip
mkdir downloads
cd downloads/
wget https://github.com/atsign-foundation/sshnoports/archive/refs/heads/trunk.zip
mv trunk sshnports.zip
wget https://github.com/atsign-foundation/at_python/archive/refs/heads/trunk.zip
mv trunk at_python.zip
cd ..
unzip downloads/at_python.zip
cd at_python-trunk/
pip install -r requirements.txt
pip install .
cd ..
unzip downloads/sshnports.zip
cd sshnoports-trunk/packages/sshnpdpy/
pip install -r requirements.txt
```

Gets to a working install of shhnpdpy (except copying keys into place).

All of the python wheels that we need are already available as OpenWRT packages :)

Next steps... we can create an python3-at_python package that pulls in all of the dependencies, and we can then create a python3-sshnpdpy package that depends on that. Then it should simply be a case of `opkg install python3-sshnpdpy` to get a working install.

**Comment by cpswan** [comment] 2023-10-12 12:19
Another step along the way. Here's a package for the at_python SDK (for RPi 32 bit):

[python3-atpython_0.0.1-1_arm_cortex-a7_neon-vfpv4.ipk.zip](https://github.com/atsign-foundation/sshnoports/files/12882216/python3-atpython_0.0.1-1_arm_cortex-a7_neon-vfpv4.ipk.zip)

Source at https://github.com/atsign-foundation/Atsign_OpenWRT_packages

**Comment by cpswan** [comment] 2023-10-13 15:30
With https://github.com/atsign-foundation/sshnoports/issues/164 done we can now create packages for Python sshnpd

But... I don't think that's generally going to be the best way to do things, as there are a LOT of architecture/version combos out there.

Generally it will be better to install the dependencies:

```
opkg install python3-light python3-bcrypt python3-cffi python3-cryptography \
  python3-dateutil python3-paramiko python3-pip python3-pycparser \
  python3-pynacl python3-requests python3-six
```
And then install at_python and sshnpdpy from wheels (which can be built using `poetry build` in the respective source).

Better still would be wheels on PyPi, but getting an org account set up there is slow going following the recent malware attacks.

@cconstab are you OK to close this, or do you want to try it yourself first?

**Closed as completed** 2023-11-02 14:36 UTC
Labels: bug
