### ISSUE TITLE
Provide ability to use no-encrypt-traffic in srv

### ISSUE THREAD

**Issue by sitaram-kalluri** [atsign-foundation/noports#1416] opened 2024-10-01 16:25 UTC
### Is your feature request related to a problem? Please describe.

Sometimes users may not want to use encrypted sockets - perhaps for example they are using a protocol which already uses encryption. This always has to be used with appropriate user caution

### Describe the solution you'd like

Always encrypt by default; if user requests no encryption then show a prominent warning

**Comment by gkc** [comment] 2024-10-02 14:29
Duplicate of #1417

**Closed as completed by gkc** 2024-10-02 14:29 UTC
Labels: enhancement
